/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.0016927,\"B\": 1.52987e-05,\"Lq\": 0.0023278,\"poleCount"
  "\": 10,\"rated_current\": 1.16,\"J\": 5.538e-06,\"velocity\": {\"nominal\": 327."
  "249234749,\"maximum\": 628.3185307,\"units\": \"rad\\/s\"},\"L\": 0.002375625,\""
  "R\": 2.8322,\"current\": {\"maximum\": {\"continuous\": 1.16,\"peak\": 1.16},\"u"
  "nits\": \"A\"},\"Ld\": 0.00242345,\"Ke\": 0.0417238369547,\"id\": \"Hurst075\"},"
  "\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": {\"f"
  "eedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,\"properties"
  "\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\": {\"min_dece"
  "leration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\": {\"errorLim"
  "it\": 0.99997,\"properties\": {\"independent\": true,\"reference\": false},\"dur"
  "ation\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fault_detect\""
  ": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"architecture\": "
  "\"classic\",\"peripherals\": {\"instances\": []},\"version\": \"5.7.1\",\"periph"
  "eral_library\": {\"name\": \"PIC24 \\/ dsPIC33 \\/ PIC32MM MCUs\",\"version\": "
  "\"1.171.5\"}},\"data_model\": {\"schema_version\": 5},\"motorBench\": {\"commit_"
  "id\": \"cca205f0cfd3911d9402cd4a9bb65183b7cd48b6\",\"version\": \"2.50.0\"},\"MC"
  "AF\": {\"build\": {\"commit_id\": \"128946\",\"date_str\": \"2025 Apr 09\",\"hos"
  "tname\": \"motor-control-mcaf-tags-builder-r8-2frc38-1-0700f-4pfpx-1fklf\",\"tim"
  "e\": 1744217130.6,\"time_iso\": \"2025-04-09T16:45:30.604389\",\"time_str\": \"2"
  "025 Apr 09 16:45\",\"type\": \"release\",\"username\": \"jenkins\",\"version\": "
  "\"R8\\/RC38\"},\"build_time\": 1744217130.6,\"build_time_iso\": \"2025-04-09T16:"
  "45:30.604389\",\"build_time_str\": \"2025 Apr 09 16:45\",\"commit_id\": \"128946"
  "\",\"version\": \"R8\\/RC38\"}},\"scdata\": {\"setup\": {\"communications\": {\""
  "baudrate\": 625000},\"analysis\": {\"spindown_time\": {\"units\": \"s\",\"value"
  "\": 1.0},\"max_motor_speed\": {\"units\": \"rad\\/s mechanical\",\"value\": 2094"
  ".4}},\"calibration\": {\"vdc\": {\"units\": \"V\",\"value\": 24.0},\"resistor\":"
  " {\"units\": \"ohms\",\"value\": 12.0}}}},\"autotune_result\": {\"current\": {\""
  "Kp\": 3.14086201967,\"phase_margin\": 80.0,\"wc\": 1566.86134344,\"Ki\": 4921.29"
  "528371,\"pi_phase_lag\": 45.0},\"velocity\": {\"Kp\": 0.00902846429247,\"phase_m"
  "argin\": 65.0,\"wc\": 93.0351954085,\"Ki\": 0.148108481716,\"pi_phase_lag\": 10."
  "0}},\"code_generation_tag_map\": {\"application\": \"sample\",\"diagnostics\": "
  "\"x2cscope\"},\"operating_range\": {\"velocity\": {\"units_qualifier\": \"mechan"
  "ical\",\"units\": \"rad\\/s\",\"minimum\": 104.7198}},\"build\": {\"hardware_spe"
  "c\": \"mclv2:33ck256mp508_extopamp_pim\",\"normfactor_associations\": [{\"contex"
  "t\": null,\"annotations\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURR"
  "ENT_ALPHABETA\",\"MCAF_U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omega"
  "Ctrl.outMin\",\"MCAF_MOTOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{"
  "\"typerefs\": [\"MCAF_MOTOR_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": "
  "15},{\"typerefs\": [\"MCAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U"
  "_VOLTAGE_DQ\",\"MCAF_U_VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_"
  "DATA.idCtrl.outMax\",\"MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl."
  "outMax\"],\"unit\": \"V\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.in"
  "tegrator\",\"MCAF_MOTOR_DATA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\""
  "typerefs\": [\"MCAF_U_DUTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\""
  "MCAF_U_ANGLE_ELEC\"],\"unit\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_A"
  "NGLE_MECH\"],\"unit\": \"theta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_"
  "MECH\"],\"unit\": \"omega_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC"
  "\"],\"unit\": \"omega_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_EL"
  "EC_DT\"],\"unit\": \"dtheta_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPER"
  "ATURE\"],\"unit\": \"Temperature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSION"
  "LESS\",\"MCAF_U_DIMENSIONLESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": ["
  "\"MCAF_U_NORMALIZED_GAIN\"],\"unit\": 1,\"q\": 14}]}]},\"drive\": {\"iout\": {\""
  "measurement\": {\"compensation\": {\"channels\": [\"a\",\"b\"],\"values\": {\"a"
  "\": [1.0,0.0],\"b\": [0.0,1.0]},\"offset\": {\"range\": 0.03125,\"samples\": 128"
  ",\"filterGain\": 0.25}}},\"time_constant\": 1.5e-06,\"fullscale\": 4.4,\"maximum"
  "\": {\"continuous\": 2.29},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\","
  "\"runtimeSelect\": false,\"atpll\": {\"tau1\": 0.0001,\"tau2\": 0.00219,\"kpfact"
  "or\": 1.9,\"kifactor\": 30},\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,"
  "\"tau\": 0.00219},\"flux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006"
  "552},\"temperature\": {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_s"
  "ampling_delay\": 0,\"period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.9777,\"mini"
  "mum\": 0.005},\"deadtime\": 2e-06},\"mcaf\": {\"adc\": {\"triggerSettings\": {\""
  "noTrigger\": \"NO_TRIGGER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1"
  "_TRIGGER2\"},\"channels\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CU"
  "RRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAG"
  "E\"],\"required\": {\"single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\","
  "\"POTENTIOMETER\"],\"dual_channel\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DC"
  "LINK_VOLTAGE\",\"POTENTIOMETER\"],\"triple_channel\": [\"PHASEA_CURRENT\",\"PHAS"
  "EB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"]},\"optiona"
  "l\": [\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHASEC_VOLTAGE\",\"BRIDGE_TEMPERAT"
  "URE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\"name\": \"PHASEA_CURRENT\",\"c_fragm"
  "ent\": \"PhaseACurrent\",\"description\": \"phase A current\",\"type\": \"curren"
  "t\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragment\": \"PhaseBCurrent\",\"descripti"
  "on\": \"phase B current\",\"type\": \"current\"},{\"name\": \"PHASEC_CURRENT\","
  "\"c_fragment\": \"PhaseCCurrent\",\"description\": \"phase C current\",\"type\":"
  " \"current\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fragment\": \"PhaseAVoltage\",\""
  "description\": \"phase A voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEB_VO"
  "LTAGE\",\"c_fragment\": \"PhaseBVoltage\",\"description\": \"phase B voltage\","
  "\"type\": \"voltage\"},{\"name\": \"PHASEC_VOLTAGE\",\"c_fragment\": \"PhaseCVol"
  "tage\",\"description\": \"phase C voltage\",\"type\": \"voltage\"},{\"name\": \""
  "DCLINK_CURRENT\",\"c_fragment\": \"DCLinkCurrent\",\"description\": \"DC link cu"
  "rrent\",\"type\": \"current\"},{\"name\": \"DCLINK_VOLTAGE\",\"c_fragment\": \"D"
  "CLinkVoltage\",\"description\": \"DC link voltage\",\"type\": \"voltage\"},{\"na"
  "me\": \"POTENTIOMETER\",\"c_fragment\": \"Potentiometer\",\"description\": \"pot"
  "entiometer voltage\",\"type\": \"voltage\"},{\"name\": \"BRIDGE_TEMPERATURE\",\""
  "c_fragment\": \"BridgeTemperature\",\"description\": \"bridge temperature voltag"
  "e\",\"type\": \"voltage\"},{\"name\": \"ABSREF_VOLTAGE\",\"c_fragment\": \"Absol"
  "uteReferenceVoltage\",\"description\": \"absolute reference voltage\",\"type\": "
  "\"voltage\"}]}}},\"metadata\": {\"name\": \"MCLV-2\",\"id\": \"mclv2\"},\"vdc\":"
  " {\"nominal\": 24.0,\"time_constant\": 0.000188,\"fullscale\": 52.8,\"maximum\":"
  " 26.0,\"units\": \"V\",\"minimum\": 16.0},\"configuration\": {\"characteristics"
  "\": {\"current\": {\"dcLink\": {\"fullscale\": 4.4,\"timeConstant\": 1.5e-06},\""
  "phase\": {\"fullscale\": 4.4,\"gainCorrectionFactors\": {\"Kaa\": 0.891,\"Kab\":"
  " -0.03,\"Kba\": -0.004,\"Kbb\": 0.965,\"Kcc\": 1.0},\"maximum\": {\"continuous\""
  ": 2.29},\"timeConstant\": 1.5e-06}},\"device\": \"dsPIC33EP256MC506\",\"pwm\": {"
  "\"deadTime\": {\"default\": 2e-06,\"maximum\": 6e-06,\"minimum\": 2e-06},\"dutyC"
  "ycle\": {\"maximum\": 0.9777,\"minimum\": 0.005},\"frequency\": {\"default\": 20"
  "000,\"maximum\": 50000,\"minimum\": 1000}},\"voltage\": {\"dcLink\": {\"default"
  "\": 24.0,\"fullscale\": 52.8,\"maximum\": 26.0,\"minimum\": 16.0,\"timeConstant"
  "\": 0.000188},\"phase\": {\"fullscale\": 52.8,\"timeConstant\": 0.000188}}},\"id"
  "entification\": {\"description\": \"dsPICDEM&trade; MCLV-2 Development Board\","
  "\"displayName\": \"MCLV-2\",\"id\": \"mclv2\",\"pim_id\": \"33ep256mc506_extopam"
  "p_pim\"},\"peripherals\": {\"adc\": {\"current\": {\"a\": {\"channel\": \"AN1\","
  "\"inverted\": true,\"signed\": true},\"b\": {\"channel\": \"AN4\",\"inverted\": "
  "true,\"signed\": true},\"dcLink\": {\"channel\": \"AN8\",\"inverted\": false,\"s"
  "igned\": true}},\"other\": {\"potentiometer\": {\"channel\": \"AN13\",\"signed\""
  ": true}},\"samplingTime\": {\"default\": 3e-07,\"maximum\": 1e-06,\"minimum\": 3"
  "e-07},\"voltage\": {\"dcLink\": {\"channel\": \"AN10\",\"signed\": true}}},\"deb"
  "ugger\": {\"channel\": 3},\"gpio\": {\"MCAF_BUTTON1\": {\"direction\": \"input\""
  ",\"pin\": \"RG7\",\"polarity\": \"active-high\"},\"MCAF_BUTTON2\": {\"direction"
  "\": \"input\",\"pin\": \"RG6\",\"polarity\": \"active-high\"},\"MCAF_LED1\": {\""
  "direction\": \"output\",\"pin\": \"RD6\",\"polarity\": \"active-high\"},\"MCAF_L"
  "ED2\": {\"direction\": \"output\",\"pin\": \"RD5\",\"polarity\": \"active-high\""
  "},\"MCAF_TESTPOINT1\": {\"direction\": \"output\",\"pin\": \"RD8\",\"polarity\":"
  " \"active-high\"}},\"oscillator\": {\"clockSource\": \"crystal oscillator\",\"in"
  "putClockFrequency\": 8000000},\"pwm\": {\"fault\": {\"polarity\": \"active-low\""
  ",\"source\": \"PCI19\"},\"generators\": {\"a\": 1,\"b\": 2,\"c\": 3},\"polarity"
  "\": {\"lower\": \"active-high\",\"upper\": \"active-high\"}},\"qei\": {\"pins\":"
  " {\"A\": \"RA8\",\"B\": \"RC6\",\"Z\": \"RF0\"}},\"uart\": {\"pins\": {\"RX\": "
  "\"RC5\",\"TX\": \"RF1\"}}}},\"idc\": {\"units\": \"A\"},\"sampling_time\": {\"cu"
  "rrent\": 5e-05,\"velocity\": 0.001},\"processor\": {\"clock_frequency\": 7000000"
  "0.0,\"device\": \"dsPIC33EP256MC506\"}},\"config\": {\"ui\": {\"content\": {\"cu"
  "rrent_measure-method\": \"dual_channel\",\"current_measure-single_channel-minimu"
  "mTime\": 2.0,\"current_measure-single_channel-sampleDelay\": 0.0,\"current_measu"
  "re-opamp-full_input_range\": true,\"estimator-type\": \"pll\",\"estimator-active"
  "-pll\": false,\"estimator-active-qei\": false,\"estimator-active-smo\": false,\""
  "estimator-active-atpll\": false,\"estimator-active-zsmt\": false,\"estimator-act"
  "ive-ideal\": false,\"operation-min_velocity_ratio\": 0.25,\"operation-startup_ve"
  "locity_ratio\": 0.2744,\"operation-max_velocity_ratio\": 1.25,\"operation-fullsc"
  "ale_base_ratio\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"operation-sa"
  "liency-threshold\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewrate-"
  "decel\": 1.0,\"operation-dyn_current_type\": \"none\",\"operation-stopping-type"
  "\": \"minimal_impact\",\"operation-stopping-closed_loop_parameters-speed\": 0.05"
  ",\"operation-stopping-closed_loop_parameters-time\": 0.5,\"operation-stopping-co"
  "astdown-end_velocity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"fault_"
  "inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_data\": false,\"fault_"
  "inject-get_tf-raise_value_error\": false,\"fault_inject-get_tf-raise_custom_erro"
  "r\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false,"
  "\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_injec"
  "t-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_control-eqn_based-ilimi"
  "t-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,"
  "\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxwe"
  "ak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-"
  "eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-"
  "perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,"
  "\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 2.0,\"f"
  "ault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable\": true,\"startu"
  "p-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startup"
  "-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-to"
  "rque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\"s"
  "tartup-theta_converge_rate\": 1.0,\"startup-method\": \"classic\",\"startup-damp"
  "ing-Imax\": 0.1,\"startup-damping-gainmax\": 40.0,\"startup-damping-omega_min\":"
  " 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,\"overmo"
  "dulation-include_duty_clipping\": true,\"pll-tau\": 2.19,\"pll-omega1\": 116.5,"
  "\"pll-velocity_filter_threshold\": 1.0,\"encoder-lines\": 250.0,\"encoder-index_"
  "present\": false,\"encoder-tracking_loop-tau\": 1.5,\"encoder-qei_sync-method\":"
  " \"align\",\"encoder-qei_sync-align-t_align\": 0.5,\"encoder-qei_sync-align-angl"
  "e_shift\": 30.0,\"encoder-qei_sync-align-angle_init\": -30.0,\"encoder-qei_sync-"
  "align_sweep-sweep_rate_pow\": 1.0,\"encoder-qei_sync-align_sweep-setup_angle\": "
  "45.0,\"encoder-qei_sync-pullout-pullout_slip\": 0.117,\"zsmt-excitation-kV\": 0."
  "12,\"zsmt-excitation-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"z"
  "smt-pll-tau_lpf\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsmt-startup-align_"
  "delay\": 1.0,\"zsmt-startup-pll_lock_time\": 1.0,\"zsmt-startup-speed_limit\": 0"
  ".015,\"zsmt-startup-current_limit\": 0.3,\"zsmt-startup-probe_current\": 0.3,\"z"
  "smt-startup-probe_duration\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-"
  "startup-probe_blanking_time\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-min"
  "otaur-voltage_limit-vd\": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-m"
  "inotaur-converge-angle\": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-m"
  "inotaur-velocity_threshold-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-trans"
  "ition\": 0.2,\"zsmt-minotaur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correc"
  "tion-current_gain\": 0.0,\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizo"
  "n_factor\": 1.05,\"dyn_current1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"vo"
  "ltage_outerloop-tau_lpf\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop"
  "-tau\": 100.0,\"mcapi-isSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUse"
  "rFunctions_enable\": false,\"board_service-uiServiceTiming\": 1.0,\"board_servic"
  "e-uiButtonDebounceTime\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"tes"
  "t_harness-perturbation_asymmetric\": false,\"adc-vtempbridge\": false,\"adc-temp"
  "_bridge_params-threshold\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-"
  "temp_bridge_params-slewrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false"
  ",\"adc-vphaseb\": false,\"adc-vphasec\": false,\"diagnostics-method\": \"x2cscop"
  "e\"},\"version\": {\"schema\": 5.0,\"motorBench\": \"???\",\"MCAF\": \"R8\"},\"s"
  "tatus\": {\"valid\": true}}}}";